services:
  # Backend API Service
  - type: web
    name: paycile-api
    env: node
    region: oregon
    plan: starter
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: paycile-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        fromService:
          type: web
          name: paycile-frontend
          property: host

  # Frontend Static Site
  - type: web
    name: paycile-frontend
    env: static
    region: oregon
    plan: starter
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: paycile-api
          property: host

# PostgreSQL Database
databases:
  - name: paycile-db
    region: oregon
    plan: starter
    postgresMajorVersion: 15 