services:
  # Backend API Service
  - type: web
    name: paycile-api
    runtime: node
    region: oregon
    plan: standard  # Paid plan for web service
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: paycile-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001
      - key: OPENAI_API_KEY
        sync: false  # You'll need to add this manually
      - key: FRONTEND_URL
        value: https://paycile-frontend.onrender.com  # Update after deployment

  # Frontend Angular App
  - type: web
    name: paycile-frontend
    runtime: node
    region: oregon
    plan: free  # Using free plan for frontend
    rootDir: frontend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

# PostgreSQL Database
databases:
  - name: paycile-db
    region: oregon
    databaseName: paycile
    user: paycile_user
    # Using new database pricing - no plan specified, will default to basic tier
    # You can upgrade in dashboard if needed
    postgresMajorVersion: 15 