services:
  # Backend API Service
  - type: web
    name: paycile-api
    runtime: node
    region: oregon
    plan: starter
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: paycile-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001
      - key: OPENAI_API_KEY
        sync: false  # You'll need to add this manually
      - key: FRONTEND_URL
        value: https://paycile-frontend.onrender.com  # Update after deployment

  # Frontend Static Site
  - type: web
    name: paycile-frontend
    runtime: static
    region: oregon
    plan: starter
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://paycile-api.onrender.com  # Update after deployment

# PostgreSQL Database
databases:
  - name: paycile-db
    region: oregon
    plan: starter
    postgresMajorVersion: 15 